//@version=5
indicator(title='TTB Basic Levels', overlay=true, max_bars_back = 4999)

import thetradingbot/ttbcolors/1 as TTBColors

offset_val = input(title='Label Offset', defval=20)
showlabels = input(title='Show Labels', defval=true)

length = 10000 // Define the period over which to find the highest high and lowest low
RangeHigh = ta.highest(high, length)
RangeLow = ta.lowest(low, length)

zones = (RangeHigh - RangeLow) / 5
percentChange = ((RangeHigh - RangeLow) / RangeLow) * 100

level80 = RangeHigh - zones
level50 = RangeLow + 2.5 * zones
level20 = RangeLow + zones

above_level_20 = ta.crossover(close, level20)
below_level_20 = ta.crossunder(close, level20)
above_level_80 = ta.crossover(close, level80)
below_level_80 = ta.crossunder(close, level80)

// Alert conditions
if above_level_20
    alert(syminfo.ticker + " InRange", alert.freq_once_per_bar)
if below_level_20
    alert(syminfo.ticker + " LowRange", alert.freq_once_per_bar)
if above_level_80
    alert(syminfo.ticker + " HighRange", alert.freq_once_per_bar)
if below_level_80
    alert(syminfo.ticker + " InRange", alert.freq_once_per_bar)


plot(RangeHigh, title='High', color=color.new(color.red, 70), style=plot.style_circles, linewidth=2)
plot(level80, title='80%', color=color.new(color.red, 70), style=plot.style_circles, linewidth=2)
plot(level50, title='50%', color=color.new(color.gray, 70), style=plot.style_circles, linewidth=2)
plot(level20, title='20%', color=color.new(color.green, 70), style=plot.style_circles, linewidth=2)
plot(RangeLow, title='Low', color=color.new(color.green, 70), style=plot.style_circles, linewidth=2)