//@version=5
//Created by raveshave
//Displays the previous monthly/weekly/daily high/low over current price. Also shows the weekly and daily open price over current price and 50% of Previous weekl, Monthly and Daily
indicator(title='TTB Past Levels', shorttitle='TTB Past Levels', overlay=true)

//Inputs
smh = input(false, title='Prev Monthly High')
sml = input(false, title='Prev Monthly Low')
smpp = input(true, title='Prev Monthly 50%')
swh = input(true, title='Prev Weekly High')
swl = input(true, title='Prev Weekly Low')
swpp = input(true, title='Prev Weekly 50%')
sdh = input(true, title='Prev Daily High')
sdl = input(true, title='Prev Daily Low')
sdpp = input(true, title='Prev Daily 50%')
//smo = input(false, title='Monthly Open')
//swo = input(true, title='Weekly Open')
//sdo = input(true, title='Daily Open')
//s3dh = input(true, title='3Daily High')
//s3dl = input(true, title='3Daily Low')
//s3dpp = input(true, title='3Daily 50%')
//s8ho = input(true, title='8H Funding')
//sdc = input(true, title='Prev Daily Close')
//sqh = input(false, title='Prev Quarterly High')
//sql = input(false, title='Prev Quarterly Low')
//sqpp = input(true, title='Prev Quarterly 50%')
//shyh = input(false, title='Prev HalfYearly High')
//shyl = input(false, title='Prev HalfYearly Low')
//shypp = input(true, title='Prev HalfYearly 50%')
syh = input(false, title='Prev Yearly High')
syl = input(false, title='Prev Yearly Low')
sypp = input(true, title='Prev Yearly 50%')



//Tickers
pyh = request.security(syminfo.tickerid, '12M', high[1])
pyl = request.security(syminfo.tickerid, '12M', low[1])
phyh = request.security(syminfo.tickerid, '6M', high[1])
phyl = request.security(syminfo.tickerid, '6M', low[1])
pqh = request.security(syminfo.tickerid, '3M', high[1])
pql = request.security(syminfo.tickerid, '3M', low[1])
mo = request.security(syminfo.tickerid, 'M', open)
pmh = request.security(syminfo.tickerid, 'M', high[1])
pml = request.security(syminfo.tickerid, 'M', low[1])
wo = request.security(syminfo.tickerid, 'W', open)
pwh = request.security(syminfo.tickerid, 'W', high[1])
pwl = request.security(syminfo.tickerid, 'W', low[1])
do_1 = request.security(syminfo.tickerid, 'D', open)
pdh = request.security(syminfo.tickerid, 'D', high[1])
pdl = request.security(syminfo.tickerid, 'D', low[1])
pdc = request.security(syminfo.tickerid, 'D', close[1])
fnd = request.security(syminfo.tickerid, '480', open)
p3dh = request.security(syminfo.tickerid, '3D', high[1])
p3dl = request.security(syminfo.tickerid, '3D', low[1])
DPP = (pdh + pdl) / 2
WPP = (pwh + pwl) / 2
MPP = (pmh + pml) / 2
D3PP = (p3dh + p3dl) / 2
QPP = (pqh + pql) / 2
HYPP = (phyh + phyl) / 2
YPP = (pyh + pyl) / 2
//Color
moc = mo != mo[1] ? na : #7AA3AD
pmhc = pmh != pmh[1] ? na : color.blue
pmlc = pml != pml[1] ? na : color.blue
woc = wo != wo[1] ? na : #7AA3AD
pwhc = pwh != pwh[1] ? na : color.red
pwlc = pwl != pwl[1] ? na : color.red
doc = do_1 != do_1[1] ? na : #7AA3AD
pdhc = pdh != pdh[1] ? na : color.white
pdlc = pdl != pdl[1] ? na : color.white
pdcc = pdc != pdc[1] ? na : #555555
pqhc = pqh != pqh[1] ? na : color.yellow
pqlc = pql != pql[1] ? na : color.yellow
phyhc = phyh != phyh[1] ? na : color.orange
phylc = phyl != phyl[1] ? na : color.orange
pyhc = pyh != pyh[1] ? na : #444444
pylc = pyl != pyl[1] ? na : #D96867

//Plots
//plot(smo and mo ? mo : na, title='Monthly Open', style=plot.style_line, linewidth=1, color=moc)
plot(smh and pmh ? pmh : na, title='Prev Monthly High', style=plot.style_line, linewidth=1, color=pmhc)
plot(sml and pml ? pml : na, title='Prev Monthly Low', style=plot.style_line, linewidth=1, color=pmlc)
//plot(swo and wo ? wo : na, title='Weekly Open', style=plot.style_line, linewidth=1, color=woc)
plot(swh and pwh ? pwh : na, title='Prev Weekly High', style=plot.style_line, linewidth=1, color=pwhc)
plot(swl and pwl ? pwl : na, title='Prev Weekly Low', style=plot.style_line, linewidth=1, color=pwlc)
//plot(sdo and do_1 ? do_1 : na, title='Daily Open', style=plot.style_line, linewidth=1, color=doc)
plot(sdh and pdh ? pdh : na, title='Prev Daily High', style=plot.style_line, linewidth=1, color=pdhc)
plot(sdl and pdl ? pdl : na, title='Prev Daily Low', style=plot.style_line, linewidth=1, color=pdlc)
//plot(sdc and pdc ? pdc : na, title='Prev Daily Close', style=plot.style_line, linewidth=1, color=pdcc)
plot(sdpp and DPP ? DPP : na, color=color.new(color.yellow, 0), title='Daily 50%', style=plot.style_circles, linewidth=1)
plot(swpp and WPP ? WPP : na, color=color.new(color.blue, 0), title='Weekly 50%', style=plot.style_circles, linewidth=1)
plot(smpp and MPP ? MPP : na, color=color.new(color.red, 0), title='Monthly 50%', style=plot.style_circles, linewidth=1)
//plot(s8ho and fnd ? fnd : na, title='8H Funding', style=plot.style_line, linewidth=1)
//plot(s3dh and p3dh ? p3dh : na, title='Prev 3Daily High', style=plot.style_line, linewidth=1, color=pdhc)
//plot(s3dl and p3dl ? p3dl : na, title='Prev 3Daily Low', style=plot.style_line, linewidth=1, color=pdlc)
//plot(s3dpp and D3PP ? D3PP : na, color=color.new(color.yellow, 0), title='3Daily 50%', style=plot.style_circles, linewidth=1)
//plot(shyh and phyh ? phyh : na, title='Prev HalfYearly High', style=plot.style_line, linewidth=1, color=phyhc)
//plot(shyl and phyl ? phyl : na, title='Prev Halfyearly Low', style=plot.style_line, linewidth=1, color=phylc)
//plot(sqh and pqh ? pqh : na, title='Prev Quarterly High', style=plot.style_line, linewidth=1, color=pqhc)
//plot(sql and pql ? pql : na, title='Prev Quarterly Low', style=plot.style_line, linewidth=1, color=pqlc)
plot(syh and pyh ? pyh : na, title='Prev Yearly High', style=plot.style_line, linewidth=1, color=pyhc)
plot(syl and pyl ? pyl : na, title='Prev Yearly Low', style=plot.style_line, linewidth=1, color=pylc)
//plot(shypp and HYPP ? HYPP : na, title='Prev HalfYearly 50%', style=plot.style_circles, linewidth=1, color=phyhc)
//plot(sqpp and QPP ? QPP : na, title='Prev Quarterly 50%', style=plot.style_circles, linewidth=1, color=pqhc)
plot(sypp and YPP ? YPP : na, title='Prev Yearly 50%', style=plot.style_circles, linewidth=1, color=pylc)

