//@version=5
indicator("Supertrend", overlay = true, timeframe = "", timeframe_gaps = true)

source = input(close, title="Source")
atrPeriod = input.int(10,    "ATR Length", minval = 1)
factor =    input.float(3.0, "Factor",     minval = 0.01, step = 0.01)


// My main colors
var color colorUp = color.new(color.rgb(20, 225, 255), 0) // #14e1ff
var color colorDown = color.new(color.rgb(191, 54, 255), 0) // #bf36ff
var color colorUplight = color.new(#74ecff, 0) // #14e1ff
var color colorDownlight = color.new(#e4acfe, 0) // #bf36ff
var color colorNeutral = color.new(color.rgb(255, 209, 184), 0) // #FFD1B8
var color colorUpPlus = color.new(color.rgb(76, 161, 255), 0) // #4CA1FF
var color colorDownPlus = color.new(color.rgb(220, 56, 250), 0) // #dc38fa

//my trans colors
var color colorUptrans = color.new(color.rgb(20, 225, 255), 85) // #14e1ff
var color colorDowntrans = color.new(color.rgb(191, 54, 255), 85) // #bf36ff
var color colorNeutraltrans = color.new(color.rgb(255, 209, 184), 85) // #FFD1B8
var color colorUpPlustrans = color.new(color.rgb(76, 161, 255), 85) // #4CA1FF
var color colorDownPlustrans = color.new(color.rgb(220, 56, 250), 85) // #dc38fa
var color colorBlackish = color.new(color.rgb(220, 56, 250), 0) // #dc38fa

[supertrend, direction] = ta.supertrend(factor, atrPeriod)

supertrend := barstate.isfirst ? na : supertrend
upTrend =    plot(direction < 0 ? supertrend : na, "Up Trend",   color = colorUp, style = plot.style_linebr)
downTrend =  plot(direction < 0 ? na : supertrend, "Down Trend", color = colorDown,   style = plot.style_linebr)
bodyMiddle = plot(barstate.isfirst ? na : (open + close) / 2, "Body Middle",display = display.none)

fill(bodyMiddle, upTrend,   colorUptrans, fillgaps = false)
fill(bodyMiddle, downTrend, colorDowntrans, fillgaps = false)

alertcondition(direction[1] > direction, title='Downtrend to Uptrend', message='The Supertrend value switched from Downtrend to Uptrend ')
alertcondition(direction[1] < direction, title='Uptrend to Downtrend', message='The Supertrend value switched from Uptrend to Downtrend')
alertcondition(direction[1] != direction, title='Trend Change', message='The Supertrend value switched from Uptrend to Downtrend or vice versa')
