//@version=5
indicator(title='TTB Signal Store', shorttitle='TTB Signal Store', overlay=true)

groupTitleGeneralInputs = "General Inputs"
long_signal = input(title='Long Signal value', defval=1, group = groupTitleGeneralInputs)
short_signal = input(title='Short Signal value', defval=-1, group = groupTitleGeneralInputs)
signal_source = input(defval=close, title="Signal Source", group = groupTitleGeneralInputs)

// Add a user input to act as a reset trigger
reset_signals = input(title='Reset Signals', defval=false, group = groupTitleGeneralInputs)

// Declare a variable to store the historical values of the signals
var float signal_history = 0

// Reset the history variable when the user toggles the reset input
if reset_signals
    signal_history := 0
else
    if signal_source == long_signal
        signal_history := long_signal
    else if signal_source == short_signal
        signal_history := short_signal
    else
        signal_history := na

// Plot green triangle up arrow below candle when long signal is detected
plotshape(series=signal_history == long_signal, title="Long Signal", location=location.belowbar, color=color.green, style=shape.triangleup, size = size.tiny)
plotshape(series=signal_history == short_signal, title="Short Signal", location=location.abovebar, color=color.red, style=shape.triangledown, size = size.tiny)
plot(series=signal_history == long_signal ? 2 : na, title="Long Signal", color=color.green)
plot(series=signal_history == short_signal ? -2 : na, title="Short Signal", color=color.red)