//@version=5
indicator(title="TTB DMI", shorttitle="TTB DMI", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
lensig = input.int(14, title="ADX Smoothing", minval=1, maxval=50)
len = input.int(100, minval=1, title="DI Length")
up = ta.change(high)
down = -ta.change(low)
plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
trur = ta.rma(ta.tr, len)
plus = fixnan(100 * ta.rma(plusDM, len) / trur)
minus = fixnan(100 * ta.rma(minusDM, len) / trur)
sum = plus + minus
adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)
pct_diff = input.int(15, title="Percentage Difference", minval=1, maxval=100)
pct_diff_val = pct_diff / 100.0
//plot(adx, color=#F50057, title="ADX")
plot(plus, color=#37ffc3, title="+DI")
plot(minus, color=#ff75e1, title="-DI")
// Change background color based on conditions
bgcolor((plus > minus and plus > (1 + pct_diff_val) * minus) ? color.new(color.green, 90) : na, title="Green Background")
bgcolor((minus > plus and minus > (1 + pct_diff_val) * plus) ? color.new(color.red, 90) : na, title="Red Background")