//@version=5
strategy('TTB DCA 7.3L', overlay=true, initial_capital=1000000, default_qty_type=strategy.cash, default_qty_value=100000, currency=currency.USD, pyramiding=999, calc_on_every_tick=false, max_bars_back=4900)

import thetradingbot/ttbcolors/1 as TTBColors
import thetradingbot/TTB_TableBuilder/1 as TTBTableBuilder

// f_security function for MTF
f_security(_sym, _res, _src, _rep) =>
    request.security(_sym, _res, _src[not _rep and barstate.isrealtime ? 1 : 0])[_rep or barstate.isrealtime ? 0 : 1]
var bool i_repaint = false // Set to false to avoid repainting
var string ticker = syminfo.tickerid

direction = input.string(defval='Long', title='Trading Direction', options=['All', 'Long', 'Short'])
direction_text = direction == 'Long' ? 'L' : 'S'
truncate(number, decimals) =>
    factor = math.pow(10, decimals)
    int(number * factor) / factor

var long = false
var short = true

if direction == 'All'
    long := true
    short := true
    short
else if direction == 'Long'
    long := true
    short := false
    short
else if direction == 'Short'
    long := false
    short := true
    short

// Strategy Inputs
groupTitleGeneralInputs = "General Inputs"
ID = input(defval='6700960415957', title='ID', group = groupTitleGeneralInputs)
show_table = input(true, title='Show table', group = groupTitleGeneralInputs)
text_size_switch = true
HTF1= input('15', title='HTF1', group = groupTitleGeneralInputs)
HTF2= input('30', title='HTF2', group = groupTitleGeneralInputs)
HTF3= input('60', title='HTF3', group = groupTitleGeneralInputs)
HTF4= input('240', title='HTF4', group = groupTitleGeneralInputs)
HTF5= input('D', title='HTF5', group = groupTitleGeneralInputs)
MinSOBars = input(100, title="Min Bars Between SOs", group = groupTitleGeneralInputs)
version = input(defval='7-3', title='version', group = groupTitleGeneralInputs)
test = input(defval='1', title='test', group = groupTitleGeneralInputs)
// Triggers
long_trigger = input(title='Long trigger value', defval=1)
short_trigger = input(title='Short trigger value', defval=-1)
//trigger = input(defval=close, title="Enter trigger")
trigger = close

// Date Ranges
startDateTime = input.time(timestamp("1 Feb 2021 12:00"), title="Start", group="Strategy Date Range")
endDateTime = input.time(timestamp("1 Feb 2024 12:00"), title="End", group="Strategy Date Range")
window = time >= startDateTime and time <= endDateTime ? true : false 

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}
// ATRP
atrp_length = input.int(75, title='ATRP Length', minval=1, group = groupTitleGeneralInputs)

// Declare variables
var trp = float(0)
var atrp = float(0)

// Calculate true range percent
trp := ta.tr / hl2 * 100



round_to(n, decimals) =>
    mult = 1.0
    for i = 1 to decimals
        mult := mult * 10
    round_n = na(n * mult + 0.5) ? na : (n * mult + 0.5) - (n * mult + 0.5) % 1
    round_n / mult

// Calculate smoothed percentage range
atrp := round_to(ta.sma(trp, atrp_length), 4)

//atrp_htf1 = f_security(ticker, HTF1, atrp, i_repaint)
atrp_htf1 = round_to(f_security(ticker, HTF1, atrp, i_repaint), 4)
plot(atrp, title='ATRP', color=color.rgb(255, 177, 20, 94), linewidth=1, style=plot.style_linebr)
//end atrp
//-----------------------------------------------------------------------------}
groupTitleInputs = "Inputs"
safe_order_step_scale_Multiplier = input(1.35, title="Safe Order Step Scale Multiplier", group = groupTitleInputs)
price_dev = input.float(1.8, title='Price deviation to open safety orders atrp factor', step=0.1, minval=0.0, group = groupTitleInputs) * atrp / 100
tp = input.float(3.3, title='Target Take Profit atrp factor', step=0.1, minval=0.0, group = groupTitleInputs) * atrp / 100
base_lots = input.float(0.5, "Base Order Size (Lots)", group = groupTitleInputs)
SO_lots = input.float(0.5, "Safe Order Size (Lots)", group = groupTitleInputs)
SO_volume_scale = input.float(1, step=0.1, title='Safety order volume scale', group = groupTitleInputs)
SO_step_scale = input.float(1.5, step=0.1, title='Safety order step scale', group = groupTitleInputs)
max_SOs = input(6, title='max no. of safe orders', group = groupTitleInputs)

// longs
price_deviation = price_dev
take_profit = tp
base_order_lots = base_lots
safe_order_lots = SO_lots
safe_order_volume_scale = SO_volume_scale
safe_order_step_scale = SO_step_scale
max_safe_order = max_SOs

//shorts
price_S_deviation = price_dev
take_S_profit = tp
base_S_order_lots = base_lots
safe_S_order_lots = SO_lots
safe_S_order_volume_scale = SO_volume_scale
safe_S_order_step_scale = SO_step_scale
max_S_safe_order = max_SOs

base_order = base_order_lots * 100000
safe_order = safe_order_lots * 100000
base_S_order = base_S_order_lots * 100000
safe_S_order = safe_S_order_lots * 100000
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}



//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}
// supertrend
source = close
groupTitleST1 = "SuperTrend1"
atrPeriod = input.int(10,    "ATR Length", minval = 1, group = groupTitleST1)
factor =    input.float(20.0, "Factor",     minval = 0.01, step = 0.01, group = groupTitleST1)
showSTplot = input.bool(defval=false, title="Show Supertrend Plots", group = groupTitleST1)

[supertrend, ST_direction] = ta.supertrend(factor, atrPeriod)

supertrend := barstate.isfirst ? na : supertrend
upTrend =    plot(showSTplot and ST_direction < 0 ? supertrend : na, "Up Trend",   color = TTBColors.colorUp(), style = plot.style_linebr)
downTrend =  plot(showSTplot and ST_direction > 0 ? supertrend : na, "Down Trend", color = TTBColors.colorDown(),   style = plot.style_linebr)

STlongTrigger = ta.crossover(close, supertrend)
STshortTrigger = ta.crossunder(close, supertrend)
STlongFilter = ST_direction < 0
STshortFilter = ST_direction > 0

// end supertrend
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}



//-----------------------------------------------------------------------------}
// Structure
groupTitleStructureSettings = "Structure Settings"
MSlength  = input(10, 'Pivot Lookback', group = groupTitleStructureSettings)
incr    = input.float(95, 'Increment Factor %', minval = 0, group = groupTitleStructureSettings)
showStrucPlots  = input(true, "Show Struc Plots", group = groupTitleStructureSettings)

resetOn = 'CHoCH'

//Style 
bullCss    = color.rgb(7, 232, 187, 34)
bearCss    = color.rgb(250, 36, 214, 37)
retCss     = #ffbb00
areaTransp = 90

//------------------------------------------------------------------------------
//Global variables
//-----------------------------------------------------------------------------{
var float ph_y = na , var int ph_x = na
var float pl_y = na , var int pl_x = na
var float top = na  , var float btm = na
var ph_cross = false, var pl_cross = false

var float max = na
var float min = na
var float ts = na

var os = 0
ms = 0

//------------------------------------------------------------------------------
//Detect pivots and get coordinates
//-----------------------------------------------------------------------------{
n = bar_index
ph = ta.pivothigh(MSlength, MSlength)
pl = ta.pivotlow(MSlength, MSlength)

if ph > 0
    ph_y := ph
    ph_x := n - MSlength
    ph_cross := false

if pl > 0
    pl_y := pl
    pl_x := n - MSlength
    pl_cross := false


//-----------------------------------------------------------------------------}
//Bullish structures
//-----------------------------------------------------------------------------{
if close > ph_y and not ph_cross
    if resetOn == 'CHoCH'
        ms := os == -1 ? 1 : 0
    else
        ms := 1

    ph_cross := true


    os := 1

    //Search for local minima
    btm := low
    for i = 0 to (n - ph_x)-1
        btm := math.min(low[i], btm)

    osChange = os != os[1]

//-----------------------------------------------------------------------------}
//Bearish structures
//-----------------------------------------------------------------------------{
if close < pl_y and not pl_cross
    if resetOn == 'CHoCH'
        ms := os == 1 ? -1 : 0
    else
        ms := -1

    pl_cross := true

    os := -1

    //Search for local maxima
    top := high
    for i = 0 to (n - pl_x)-1
        top := math.max(high[i], top)

    osChange = os != os[1]

//-----------------------------------------------------------------------------}
//Trailing stop
//-----------------------------------------------------------------------------{
//Trailing max/min
if ms == 1
    max := close
else if ms == -1
    min := close
else
    max := math.max(close, max)
    min := math.min(close, min)

//Trailing stop
ts := ms == 1 ? btm
  : ms == -1 ? top
  : os == 1 ? ts + (max - max[1]) * incr / 100
  : ts + (min - min[1]) * incr / 100

//Plots
css = (ms > 0) ? na 
  : os == 1 ? bullCss
  : bearCss

plot_price = plot(showStrucPlots ? close : na, editable = false, display = display.none)
plot_ts    = plot(showStrucPlots ? ts : na, 'Trailing Stop', color = css)

// plot the HTF1 trailing stop
ts_htf1 = f_security(ticker, HTF1, ts, i_repaint)
plot_ys_htf1 = plot(showStrucPlots ? ts_htf1 : na, 'HTF1 Trailing Stop', color=color.rgb(255, 177, 20, 88))

// plot the HTF2 trailing stop
ts_htf2 = f_security(ticker, HTF2, ts, i_repaint)
plot_ts_htf2 = plot(showStrucPlots ? ts_htf2 : na, 'HTF2 Trailing Stop', color=color.rgb(255, 20, 145, 89))

// plot the HTF3 trailing stop
ts_htf3 = f_security(ticker, HTF3, ts, i_repaint)
plot_ts_htf3 = plot(showStrucPlots ? ts_htf3 : na, 'HTF3 Trailing Stop', color=color.rgb(239, 255, 20, 57))

// plot the HTF4 trailing stop
ts_htf4 = f_security(ticker, HTF4, ts, i_repaint)
plot_ts_htf4 = plot(showStrucPlots ? ts_htf4 : na, 'HTF4 Trailing Stop', color=color.rgb(20, 255, 20, 89))

css_area = (close - ts) * os < 0 ? retCss
  : css

//fill(plot_price, plot_ts, color.new(css_area, areaTransp))
fill(plot_price, plot_ts, color.new(showStrucPlots ? css_area : na, areaTransp))

// trend change plots
osChange = os != os[1]

trendUp = os == 1 and osChange
trendDown = os == -1 and osChange

trendingUp = os == 1
trendingDown = os == -1

//MTF os
os_htf1 = f_security(ticker, HTF1, os, i_repaint)
os_htf2 = f_security(ticker, HTF2, os, i_repaint)
os_htf3 = f_security(ticker, HTF3, os, i_repaint)
trendingUpHTF1 = os_htf1 == 1
trendingDownHTF1 = os_htf1 == -1
trendingUpHTF2 = os_htf2 == 1
trendingDownHTF2 = os_htf2 == -1
trendingUpHTF3 = os_htf3 == 1
trendingDownHTF3 = os_htf3 == -1


above_ts_htf1 = close > ts_htf1
below_ts_htf1 = close < ts_htf1
above_ts_htf2 = close > ts_htf2
below_ts_htf2 = close < ts_htf2
above_ts_htf3 = close > ts_htf3
below_ts_htf3 = close < ts_htf3
// end structure
//-----------------------------------------------------------------------------}



var current_so = 0
var current_S_so = 0
var initial_order = 0.0
var initial_S_order = 0.0
var original_ttp_value = 0.0
var quantity = 0.0
var entry_price = 0.0
var firstBarTime = 0.0
var maxDiffDays = 0.0
var soCount = 0
var SO1 = 0
var SO2 = 0
var SO3 = 0
var SO4 = 0
var SO5 = 0
var SO6 = 0
var SO7 = 0
var noSO = 0
var initial_price = 0.0
var initial_S_price = 0.0
var price_drop = 0.0
var price_pump = 0.0
var max_drop = 0.0
var max_pump = 0.0
var pump_date = 0
var pump_month = 0
var drop_date = 0
var drop_month = 0
var longest_trade_day = 0
var longest_trade_month = 0
var take_profit_level = 0.0
var take_S_profit_level = 0.0
var tp_plot = 0.0
var tp_S_plot = 0.0
var threshold = 0.0
var S_threshold = 0.0
timeDiff = time - firstBarTime
maxDev = 0.0
maxSDev = 0.0
closedTrades = 0
var tradeCount = 0
var i = 0
var avg_price = 0.0
var total_funds_in_trade = 0.0
var total_qty_in_trade = 0.0
var capital = 100.0

// Turn that time difference into days
diffDays = timeDiff / 86400000

// Calculate our TP levels
take_profit_level := avg_price * (1 + take_profit)
take_S_profit_level := avg_price * (1 - take_S_profit)

var int entry_bar_index = na
var int last_so_bar = na
min_bars_between_sos = MinSOBars // Minimum number of bars between SOs

so_multiplier_4 = input(1.5, title="Multiplier for SO4", group = groupTitleInputs)
so_multiplier_5_6 = input(2.0, title="Multiplier for SO5 and SO6", group = groupTitleInputs)
so_multiplier = current_so == 4 ? so_multiplier_4 : current_so >= 5 and current_so <= 6 ? so_multiplier_5_6 : 1

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}
//Long and short entry
///Strategy Inputs
groupTitleLongEntry = "Long Entry"
trigger_long_Input = input.bool(false, "Trigger Long", group = groupTitleLongEntry)
Struc_trigger_long_Input = input.bool(true, "Struc Trigger Long", group = groupTitleLongEntry)
STlongTriggerInput = input.bool(false, "ST Long Trigger", group = groupTitleLongEntry)

groupTitleLongFilters = "Long Filters"
STlongFilterInput = input.bool(false, "ST Long Filter", group = groupTitleLongFilters)
above_ts_htf1_filter = input.bool(false, "Use hft1 long trend filter", group = groupTitleLongFilters)
above_ts_htf2_filter = input.bool(false, "Use hft2 long trend filter", group = groupTitleLongFilters)
above_ts_htf3_filter = input.bool(true, "Use hft3 long trend filter", group = groupTitleLongFilters)
above_ts_htf4_filter = input.bool(false, "Use hft4 long trend filter", group = groupTitleLongFilters)
above_ts_htf5_filter = input.bool(false, "Use hft5 long trend filter", group = groupTitleLongFilters)


groupTitleShortEntry = "Short Entry"
trigger_short_Input = input.bool(false, "Trigger Short", group = groupTitleShortEntry)
Struc_trigger_short_Input = input.bool(false, "Struc Trigger Short", group = groupTitleShortEntry)
STshortTriggerInput = input.bool(false, "ST Short Trigger", group = groupTitleShortEntry)

groupTitleShortFilters = "Short Filters"
STshortFilterInput = input.bool(false, "ST Short Filter", group = groupTitleShortFilters)
below_ts_htf1_filter = input.bool(false, "Use hft1 short trend filter", group = groupTitleShortFilters)
below_ts_htf2_filter = input.bool(false, "Use hft2 short trend filter", group = groupTitleShortFilters)
below_ts_htf3_filter = input.bool(false, "Use hft3 short trend filter", group = groupTitleShortFilters)
below_ts_htf4_filter = input.bool(false, "Use hft4 short trend filter", group = groupTitleShortFilters)
below_ts_htf5_filter = input.bool(false, "Use hft5 short trend filter", group = groupTitleShortFilters)

groupTitleSOsExitLong = "Long SOs and Exit"
trendingUp_filterSO = input.bool(true, "trendingUp long trend filter for SO", group = groupTitleSOsExitLong)
above_ts_htf1_filterSO = input.bool(false, "Use hft1 long trend filter for SO", group = groupTitleSOsExitLong)
above_ts_htf2_filterSO = input.bool(false, "Use hft2 long trend filterfor SO", group = groupTitleSOsExitLong)
above_ts_htf3_filterSO = input.bool(true, "Use hft3 long trend filter for SO", group = groupTitleSOsExitLong)
above_ts_htf4_filterSO = input.bool(false, "Use hft4 long trend filter for SO", group = groupTitleSOsExitLong)
above_ts_htf5_filterSO = input.bool(false, "Use hft5 long trend filter for SO", group = groupTitleSOsExitLong)


groupTitleSOsExitShort = "Short SOs and Exit"
trendingDown_filterSO = input.bool(false, "trendingDown short trend filter for SO", group = groupTitleSOsExitShort)
below_ts_htf1_filterSO = input.bool(false, "Use hft1 short trend filter for SO", group = groupTitleSOsExitShort)
below_ts_htf2_filterSO = input.bool(false, "Use hft2 short trend filter for SO", group = groupTitleSOsExitShort)
below_ts_htf3_filterSO = input.bool(false, "Use hft3 short trend filter for SO", group = groupTitleSOsExitShort)
below_ts_htf4_filterSO = input.bool(false, "Use hft4 short trend filter for SO", group = groupTitleSOsExitShort)
below_ts_htf5_filterSO = input.bool(false, "Use hft5 short trend filter for SO", group = groupTitleSOsExitShort)

// First Position
//for i = 0 to max_safe_order - 1 by 1
for j = 0 to max_safe_order - 1 by 1
    maxDev := int((maxDev + price_deviation * 100 * math.pow(safe_order_step_scale, i)) * 100) / 100
    maxDev
//for i = 0 to max_S_safe_order - 1 by 1
for j = 0 to max_S_safe_order - 1 by 1
    maxSDev := int((maxSDev + price_S_deviation * 100 * math.pow(safe_S_order_step_scale, i)) * 100) / 100
    maxSDev

//strategy.close_all(math.abs(strategy.position_size) != 0 and current_so[1] == 0)
if math.abs(strategy.position_size) != 0 and current_so[1] == 0
    strategy.close_all()

var int longEntryBarIndex = na
var int shortEntryBarIndex = na
// for the BE stoploss
var bool hasReachedHalfwayLong = na
var float halfTakeProfitLevelLong = na
var bool hasReachedHalfwayShort = na
var float halfTakeProfitLevelShort = na


if long and strategy.position_size == 0 and close > 0 and window and not(hour(time) == 0 and minute(time) < 59) and (trigger_long_Input ? trigger == long_trigger : true) and (Struc_trigger_long_Input ? trendUp : true) and (above_ts_htf3_filter ? above_ts_htf3 : true) 
    _string_long = 'type=order,order-type=long,symbol=' + syminfo.ticker + '.PRO' + ',risk=' + str.tostring(base_order_lots) + ',comment="' + version + '-' + test + direction_text + '",entry=true'
    strategy.entry('Long @' + str.tostring(close), strategy.long, qty=base_order_lots * 100000, alert_message=_string_long)
    initial_order := close
    current_so := 1
    initial_price := close
    price_drop := close
    original_ttp_value := 0
    firstBarTime := time
    tradeCount += 1
    avg_price := close
    total_funds_in_trade := avg_price * base_order_lots * 100000
    total_qty_in_trade := base_order_lots * 100000
    entry_bar_index := bar_index


else if short and strategy.position_size == 0 and close > 0 and window and not(hour(time) == 0 and minute(time) < 59) and (trigger_short_Input ? trigger == short_trigger : true) and (Struc_trigger_short_Input ? trendDown : true) and (below_ts_htf3_filter ? below_ts_htf3 : true)
    _string_short = 'type=order,order-type=short,symbol=' + syminfo.ticker + '.PRO' + ',risk=' + str.tostring(base_S_order_lots) + ',comment="' + version + '-' + test + direction_text + '",entry=true'
    strategy.entry('Short @' + str.tostring(close), strategy.short, qty=base_S_order_lots * 100000, alert_message=_string_short)
    initial_S_order := close
    current_so := 1
    firstBarTime := time
    tradeCount += 1
    initial_S_price := close
    price_pump := close
    avg_price := close
    total_funds_in_trade := avg_price * base_S_order_lots * 100000
    total_qty_in_trade := base_S_order_lots * 100000
    //total_qty_in_trade
    entry_bar_index := bar_index


//makes the red and green line plot pretty at the position opening
if strategy.position_size == 0
    threshold := low[1]
    S_threshold := high[1]
    S_threshold


//Safety order levels
if strategy.position_size > 0 and i == 0
    if safe_order_step_scale == 1.0
        threshold := initial_order - initial_order * price_deviation * safe_order_step_scale * safe_order_step_scale_Multiplier * current_so
        threshold
    else
        threshold := initial_order - initial_order * (price_deviation * (math.pow(safe_order_step_scale * safe_order_step_scale_Multiplier, current_so) - 1) / (safe_order_step_scale - 1))
        threshold

// Modify the calculation of the threshold for short positions
else if strategy.position_size < 0 and i == 0
    if safe_S_order_step_scale == 1.0
        S_threshold := initial_S_order * (1 + price_S_deviation * current_so)
        S_threshold
    else
        S_threshold := initial_S_order * (1 + price_S_deviation * (math.pow(safe_S_order_step_scale * safe_order_step_scale_Multiplier, current_so) - 1) / (safe_S_order_step_scale - 1))
        S_threshold


// Long SO (Average Down)
if current_so > 0 and i == 0 and strategy.position_size > 0 and low <= threshold and current_so <= max_safe_order and not(hour(time) == 0 and minute(time) < 59) and (na(last_so_bar) or bar_index > last_so_bar + min_bars_between_sos) and (trendingUp_filterSO ? trendingUp : true) and (above_ts_htf3_filterSO ? above_ts_htf3 : true)
    _string_long_so = 'type=order,order-type=long,symbol=' + str.replace(syminfo.ticker, " ", "") + '.PRO' + ',risk=' + str.tostring(base_order_lots * so_multiplier * math.pow(safe_order_volume_scale, current_so - 1)) + ',comment="' + version + '-' + test + direction_text + '",entry=false'
    strategy.entry('SO ' + str.tostring(current_so) + '@' + str.tostring(close), strategy.long, qty=base_order * so_multiplier * math.pow(safe_order_volume_scale, current_so - 1), alert_message=_string_long_so)
    total_funds_in_trade := total_funds_in_trade + threshold * base_order * so_multiplier * math.pow(safe_order_volume_scale, current_so - 1)
    total_qty_in_trade := total_qty_in_trade + base_order * so_multiplier * math.pow(safe_order_volume_scale, current_so - 1)
    avg_price := total_funds_in_trade / total_qty_in_trade
    current_so += 1
    tradeCount += 1
    last_so_bar := bar_index // Update the bar index when an SO is executed



// Short SO (Average Up)
if current_so > 0 and 
   i == 0 and 
   strategy.position_size < 0 and 
   high >= S_threshold and 
   current_so <= max_S_safe_order and 
   not(hour(time) == 0 and minute(time) < 59) and 
   (na(last_so_bar) or bar_index > last_so_bar + min_bars_between_sos) and 
   (trendingDown_filterSO ? trendingDown : true) and 
   (below_ts_htf3_filterSO ? below_ts_htf3 : true) 
    _string_short_so = 'type=order,order-type=short,symbol=' + str.replace(syminfo.ticker, " ", "") + '.PRO' + ',risk=' + str.tostring(base_S_order_lots * so_multiplier * math.pow(safe_S_order_volume_scale, current_so - 1)) + ',comment="' + version + '-' + test + direction_text + '",entry=false'
    strategy.entry('SSO ' + str.tostring(current_so) + '@' + str.tostring(close), strategy.short, qty=base_S_order * so_multiplier * math.pow(safe_S_order_volume_scale, current_so - 1), alert_message=_string_short_so)
    total_funds_in_trade := total_funds_in_trade + S_threshold * base_S_order * so_multiplier * math.pow(safe_S_order_volume_scale, current_so - 1)
    total_qty_in_trade := total_qty_in_trade + base_S_order * so_multiplier * math.pow(safe_S_order_volume_scale, current_so - 1)
    avg_price := total_funds_in_trade / total_qty_in_trade
    current_so += 1
    tradeCount += 1
    last_so_bar := bar_index // Update the bar index when an SO is executed

// Take Profit! 
if i == 1
    strategy.close_all() // Close all positions
    i := 0 // Reset the counter
    i

// If the take profit level is reached and the position is long, close the trade
if take_profit_level <= high and strategy.position_size > 0 and not(hour(time) == 0 and minute(time) < 59)
    _string_close_long = 'type=order,order-type=closelong,symbol=' + syminfo.ticker + '.PRO' + ',comment="' + version + '-' + test + direction_text + '"' // Prepare the close long order string
    strategy.close_all(comment='Close @' + str.tostring(close), alert_message=_string_close_long) // Close the long position
    soCount := current_so // Save the current scale-out count
    current_so := 0 // Reset the current scale-out count
    original_ttp_value := 0 // Reset the original take profit value
    price_drop := na // Reset the price drop value
    initial_price := na // Reset the initial price
    diffDays := time - firstBarTime // Calculate the difference in days
    if diffDays > maxDiffDays // If the difference in days is greater than the maximum difference in days
        maxDiffDays := diffDays // Update the maximum difference in days
        longest_trade_day := dayofmonth // Update the longest trade day
        longest_trade_month := month // Update the longest trade month
        longest_trade_month
    i := 1 // Reset the counter
    initial_order := 0.0 // Reset the initial order
    avg_price := na // Reset the average price
    capital *= (1 + total_qty_in_trade * take_profit / 100) // Update the capital
    entry_bar_index := na


// Take Short Profit! 
// If the take short profit level is reached and the position is short, close the trade
if take_S_profit_level >= low and strategy.position_size < 0 and not(hour(time) == 0 and minute(time) < 59)
    _string_close_short = 'type=order,order-type=closeshort,symbol=' + syminfo.ticker + '.PRO' + ',comment="' + version + '-' + test + direction_text + '"' // Prepare the close short order string
    strategy.close_all(comment='Close Short @' + str.tostring(close), alert_message=_string_close_short) // Close the short position
    soCount := current_so // Save the current scale-out count
    current_so := 0 // Reset the current scale-out count
    price_pump := na // Reset the price pump value
    initial_S_price := na // Reset the initial short price
    diffDays := time - firstBarTime // Calculate the difference in days
    if diffDays > maxDiffDays // If the difference in days is greater than the maximum difference in days
        maxDiffDays := diffDays // Update the maximum difference in days
        maxDiffDays
    initial_S_order := 0.0 // Reset the initial short order
    avg_price := na // Reset the average price
    capital *= (1 + total_qty_in_trade * take_S_profit / 100) // Update the capital
    entry_bar_index := na


//Table building and calculations
if strategy.position_size == 0
    if soCount == 1
        noSO += 1
        noSO
    else if soCount == 2
        SO1 += 1
        SO1
    else if soCount == 3
        SO2 += 1
        SO2
    else if soCount == 4
        SO3 += 1
        SO3
    else if soCount == 5
        SO4 += 1
        SO4
    else if soCount == 6
        SO5 += 1
        SO5
    else if soCount == 7
        SO6 += 1
        SO6
    else if soCount == 8
        SO7 += 1
        SO7
    soCount := 0
    soCount
closedTrades := noSO + SO1 * 2 + SO2 * 3 + SO3 * 4 + SO4 * 5 + SO5 * 6 + SO6 * 7 + SO7 * 8

if low < price_drop and window and strategy.position_size > 0
    price_drop := low
    if max_drop < int((1 - price_drop / initial_price) * 10000) / 100
        max_drop := int((1 - price_drop / initial_price) * 10000) / 100
        drop_date := dayofmonth(time)
        drop_month := month(time)
        drop_month
bgcolor(max_drop[1] < max_drop ? color.new(#0b5a64, 94) : na)

if high > price_pump and window and strategy.position_size < 0
    price_pump := high
    if max_pump < int((price_pump / initial_S_price - 1) * 10000) / 100
        max_pump := int((price_pump / initial_S_price - 1) * 10000) / 100
        pump_date := dayofmonth(time)
        pump_month := month(time)
        pump_month
bgcolor(max_pump[1] < max_pump ? color.new(#9b27b0, 89) : na)

if take_profit_level > 0 and strategy.position_size > 0
    tp_plot := take_profit_level
    tp_plot
else
    tp_plot := close
    tp_plot

if take_S_profit_level > 0 and strategy.position_size < 0
    tp_S_plot := take_S_profit_level
    tp_S_plot
else
    tp_S_plot := close
    tp_S_plot

//Plotting the levels
p1 = plot(tp_plot, color=strategy.position_size <= 0 ? na : TTBColors.colorUp()) // Up color
p2 = plot(avg_price, color=strategy.position_size == 0 ? na : TTBColors.colorNeutral()) // Neutral color
p3 = plot(threshold, color=strategy.position_size <= 0 ? na : TTBColors.colorDown()) // Down color
p4 = plot(tp_S_plot, color=strategy.position_size >= 0 ? na : TTBColors.colorUpPlus()) // UpPlus color
p5 = plot(S_threshold, color=strategy.position_size >= 0 ? na : TTBColors.colorDownPlus()) // DownPlus color
fill(p1, p2, color=strategy.position_size > 0 ? color.new(TTBColors.colorUp(), 90) : na) // Semi-transparent Up color
fill(p2, p3, strategy.position_size > 0 ? color.new(TTBColors.colorNeutral(), 90) : na) // Semi-transparent Neutral color
fill(p4, p2, color=strategy.position_size < 0 ? color.new(TTBColors.colorUpPlus(), 90) : na) // Semi-transparent UpPlus color
fill(p5, p2, color=strategy.position_size < 0 ? color.new(TTBColors.colorDownPlus(), 90) : na) // Semi-transparent DownPlus color
profit_color = strategy.openprofit < 0 ? TTBColors.colorDown() : TTBColors.colorUp() // Down color for loss, Up color for profit

text_size = text_size_switch ? size.small : size.normal

//Table formatting
if show_table
    var Table = table.new(position.bottom_right, columns=2, rows=20, border_width=1, bgcolor=color.new(#363a45, 0), border_color=color.gray)
    table.cell(table_id=Table, column=0, row=0, text_color=color.gray, text_size=text_size, text='Net Profit')
    table.cell(table_id=Table, column=1, row=0, text=str.tostring(int((capital - 100) * 100) / 100) + '%', text_size=text_size, text_color=TTBColors.colorUplight())
    table.cell(table_id=Table, column=0, row=1, text_color=color.gray, text_size=text_size, text='Max Deviation ')
    table.cell(table_id=Table, column=1, row=1, text=str.tostring(maxDev) + '%', text_size=text_size, text_color=TTBColors.colorDownlight())
    table.cell(table_id=Table, column=0, row=2, text_color=color.gray, text_size=text_size, text='Max Short Dev ')
    table.cell(table_id=Table, column=1, row=2, text=str.tostring(maxSDev) + '%', text_size=text_size, text_color=TTBColors.colorDownlight())
    table.cell(table_id=Table, column=0, row=3, text='No SO ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=3, text=str.tostring(noSO), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=4, text='SO 1 ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=4, text=str.tostring(SO1), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=5, text='SO 2 ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=5, text=str.tostring(SO2), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=6, text='SO 3 ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=6, text=str.tostring(SO3), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=7, text='SO 4 ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=7, text=str.tostring(SO4), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=8, text='SO 5 ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=8, text=str.tostring(SO5), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=9, text='SO 6 ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=9, text=str.tostring(SO6), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=10, text='SO 7 ', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=10, text=str.tostring(SO7), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=11, text='Closed/Open trades', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=11, text=str.tostring(strategy.closedtrades) + '/' + str.tostring(strategy.opentrades), text_size=text_size, text_color=TTBColors.colorNeutral())
    table.cell(table_id=Table, column=0, row=12, text='Current Deal Time', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=12, text=strategy.position_size != 0 ? str.tostring(int((time - firstBarTime) / 8640000) / 10) + ' days' : '0', text_size=text_size, text_color=color.green)
    table.cell(table_id=Table, column=0, row=13, text='Unrealized position', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=13, text=str.tostring(int(strategy.openprofit / (strategy.initial_capital + strategy.netprofit) * 10000) / 100) + ' %', text_size=text_size, text_color=profit_color)
    table.cell(table_id=Table, column=0, row=14, text='Longest deal:', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=14, text=str.tostring(int(maxDiffDays / 8640000) / 10) + ' days, ' + str.tostring(longest_trade_day) + '/' + str.tostring(longest_trade_month), text_size=text_size, text_color=TTBColors.colorDownlight())
    table.cell(table_id=Table, column=0, row=15, text='Max price drop:', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=15, text=str.tostring(max_drop) + ' %, ' + str.tostring(drop_date) + '/' + str.tostring(drop_month), text_size=text_size, text_color=TTBColors.colorDownlight())
    table.cell(table_id=Table, column=0, row=16, text='Max price pump:', text_size=text_size, text_color=color.gray)
    table.cell(table_id=Table, column=1, row=16, text=str.tostring(max_pump) + ' %, ' + str.tostring(pump_date) + '/' + str.tostring(pump_month), text_size=text_size, text_color=TTBColors.colorDownlight())

var tbb = TTBTableBuilder.new(position.bottom_left,4,2)
if barstate.isconfirmed
	header = tbb.R(0).TextColor(color.rgb(18, 247, 255)).TextSize(size.normal).Font(font.family_monospace)
	header.Text("HTF1","HTF2","HTF3","ATRP")
    tbb.R(1).TextColor(color.white).TextSize(size.small).Text("A","B","C",str.tostring(atrp)).Bg(color.rgb(255, 255, 255, 74))
	// tbb.R(2).TextColor(color.white).TextSize(size.small).Text("A","B","C")
	// tbb.R(3).TextColor(color.white).
