///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DarkWaveAlgo
// @version=5

indicator("MTF SuperTrends Nexus [DarkWaveAlgo]", shorttitle="MTF SuperTrends Nexus", overlay=true)
import DarkWaveAlgo/DarkWaveColorThemes/1 as ColorThemes

getSize(string sizeString) =>
    t = sizeString == "Auto" ? size.auto : sizeString == "Huge" ? size.huge : sizeString == "Large" ? size.large : sizeString == "Normal" ? size.normal : sizeString == "Small" ? size.small : sizeString == "Tiny" ? size.tiny : na  

_tfString(tf) =>
    str = "Chart"
    if (str.contains(tf, "H") or  (str.contains(tf, "S")) or (str.contains(tf, "D")) or (str.contains(tf, "W")) or (str.contains(tf, "M")))
        str := tf
    else if (not na(str.tonumber(tf)))
        str := tf == '180' ? "3h" : tf == '240' ? "4h" : tf == '480' ? "8h" : tf == '120' ? "2h" : tf == '60' ? "1h" : tf + "m"

tfString(tf) =>
    str = "Chart"
    if (str.contains(tf, "H") or  (str.contains(tf, "S")) or (str.contains(tf, "D")) or (str.contains(tf, "W")) or (str.contains(tf, "M")))
        str := tf
    else if (not na(str.tonumber(tf)))
        str := tf == '180' ? "3h" : tf == '240' ? "4h" : tf == '480' ? "8h" : tf == '120' ? "2h" : tf == '60' ? "1h" : tf + "m"
    else 
        str := _tfString(timeframe.period)


enableColorTheme = input.bool(true, "✅ Use a Color Theme", group="🌊 Global Input Settings 🌊")
selectedColorTheme = input.string("DarkWave Crypto", "  🎨 Color Theme", options=['DarkWave', 'Synthwave', 'DarkWave Crypto', 'Crystal Pool', 'Aquafarer', 'Mystic Armor', 
  'Futurist', 'Electric Zest', 'Stealth Ride', 'Long Trader', 'Short Trader', 'Emerald Glow', 'Gold Heist', 'Floral', 'Cobalt Twilight', 'Sunrise'], group="🌊 Global Input Settings 🌊")
fill_SuperTrends = input.bool(true, "✅ Fill SuperTrend Areas", group = "🌊 Global Input Settings 🌊")
hideLowerTimeframes = input.bool(true, "✅ Hide SuperTrends on Timeframes Lower Than the Chart", group="🌊 Global Input Settings 🌊")

color bullishColor = #00d5bfff
color bearishColor = #c2185bff
if (enableColorTheme)
    bullishColor := ColorThemes.getThemeColor(selectedColorTheme, 'Bullish')
    bearishColor := ColorThemes.getThemeColor(selectedColorTheme, 'Bearish')

mid = (open + close) / 2
bodyMiddle = plot(mid, display=display.none, editable=false)


SuperTrend1_Enabled = input.bool(true, "✅ Enable", group="🌊 TimeFrame #1 🌊")
SuperTrend1_Timeframe = input.timeframe("30", "  🥽 Timeframe", group="🌊 TimeFrame #1 🌊")
SuperTrend1_Period = input.int(50, "  🔎 Period", group="🌊 TimeFrame #1 🌊")
SuperTrend1_Factor = input.float(3.0, "  ⚙️ Factor", group="🌊 TimeFrame #1 🌊")
SuperTrend1_BullishColor = input.color(color.rgb(54, 255, 58), "    🖌️ Bullish Color", group="🌊 TimeFrame #1 🌊", inline="Colors")
SuperTrend1_BearishColor = input.color(color.rgb(255, 61, 61), "    🖌️ Bearish Color", group="🌊 TimeFrame #1 🌊", inline="Colors")
SuperTrend1_LabelEnabled = input.bool(true, "✅ Enable Label", group="🌊 TimeFrame #1 🌊")
SuperTrend1_LabelSize = input.string("Normal", "  📐 Size", options=["Auto", "Tiny", "Small", "Normal", "Large", "Huge"], group="🌊 TimeFrame #1 🌊")
SuperTrend1_LabelOffsetInBars = input.int(35, "  📏 Label Offset (in Bars)", group="🌊 TimeFrame #1 🌊")
SuperTrend1_ShowLabelLine = input.bool(true, "✅ Show Label Line", group="🌊 TimeFrame #1 🌊")

SuperTrend1_Hidden = hideLowerTimeframes and (timeframe.in_seconds() > timeframe.in_seconds(SuperTrend1_Timeframe))
_SuperTrend1_BearishColor = enableColorTheme ? bearishColor : SuperTrend1_BearishColor
_SuperTrend1_BullishColor = enableColorTheme ? bullishColor : SuperTrend1_BullishColor
[_SuperTrend1_Value, _SuperTrend1_Direction] =  request.security(syminfo.ticker, SuperTrend1_Timeframe, ta.supertrend(SuperTrend1_Factor, SuperTrend1_Period), barmerge.gaps_off, barmerge.lookahead_off)
SuperTrend1_Value = SuperTrend1_Enabled and not SuperTrend1_Hidden ? _SuperTrend1_Value : na
SuperTrend1_Direction = SuperTrend1_Enabled and not SuperTrend1_Hidden ? _SuperTrend1_Direction : na
SuperTrend1_Color = SuperTrend1_Direction > 0 ? _SuperTrend1_BullishColor : _SuperTrend1_BearishColor
_SuperTrend1_Color = SuperTrend1_Color
ST1_Long = plot(SuperTrend1_Enabled and SuperTrend1_Direction > 0 ? SuperTrend1_Value : na, color=_SuperTrend1_Color, linewidth=1, style = plot.style_linebr, title="🌊 TimeFrame #1 🌊 Long SuperTrend", join = true)
ST1_Short = plot(SuperTrend1_Enabled and SuperTrend1_Direction < 0 ? SuperTrend1_Value : na, color=_SuperTrend1_Color, linewidth=1, style = plot.style_linebr, title="🌊 TimeFrame #1 🌊 Short SuperTrend", join = true)
fill(ST1_Long, bodyMiddle, color = color.new(_SuperTrend1_Color, 90), fillgaps = false, display = fill_SuperTrends ? display.all : display.none)
fill(ST1_Short, bodyMiddle, color = color.new(_SuperTrend1_Color, 90), fillgaps = false, display = fill_SuperTrends ? display.all : display.none)

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

SuperTrend2_Enabled = input.bool(true, "✅ Enable", group="🌊 TimeFrame #2 🌊")
SuperTrend2_Timeframe = input.timeframe("240", "  🥽 Timeframe", group="🌊 TimeFrame #2 🌊")
SuperTrend2_Period = input.int(50, "  🔎 Period", group="🌊 TimeFrame #2 🌊")
SuperTrend2_Factor = input.float(3.0, "  ⚙️ Factor", group="🌊 TimeFrame #2 🌊")
SuperTrend2_BullishColor = input.color(color.rgb(54, 233, 58), "    🖌️ Bullish Color", group="🌊 TimeFrame #2 🌊", inline="Colors")
SuperTrend2_BearishColor = input.color(color.rgb(233, 61, 61), "    🖌️ Bearish Color", group="🌊 TimeFrame #2 🌊", inline="Colors")
SuperTrend2_LabelEnabled = input.bool(true, "✅ Enable Label", group="🌊 TimeFrame #2 🌊")
SuperTrend2_LabelSize = input.string("Normal", "  📐 Size", options=["Auto", "Tiny", "Small", "Normal", "Large", "Huge"], group="🌊 TimeFrame #2 🌊")
SuperTrend2_LabelOffsetInBars = input.int(35, "  📏 Label Offset (in Bars)", group="🌊 TimeFrame #2 🌊")
SuperTrend2_ShowLabelLine = input.bool(true, "✅ Show Label Line", group="🌊 TimeFrame #2 🌊")

SuperTrend2_Hidden = hideLowerTimeframes and (timeframe.in_seconds() > timeframe.in_seconds(SuperTrend2_Timeframe))
_SuperTrend2_BearishColor = enableColorTheme ? bearishColor : SuperTrend2_BearishColor
_SuperTrend2_BullishColor = enableColorTheme ? bullishColor : SuperTrend2_BullishColor
[_SuperTrend2_Value, _SuperTrend2_Direction] =  request.security(syminfo.ticker, SuperTrend2_Timeframe, ta.supertrend(SuperTrend2_Factor, SuperTrend2_Period), barmerge.gaps_off, barmerge.lookahead_off)
SuperTrend2_Value = SuperTrend2_Enabled and not SuperTrend2_Hidden ? _SuperTrend2_Value : na
SuperTrend2_Direction = SuperTrend2_Enabled and not SuperTrend2_Hidden ? _SuperTrend2_Direction : na
SuperTrend2_Color = SuperTrend2_Direction > 0 ? _SuperTrend2_BullishColor : _SuperTrend2_BearishColor
_SuperTrend2_Color = SuperTrend2_Color
ST2_Long = plot(SuperTrend2_Enabled and SuperTrend2_Direction > 0 ? SuperTrend2_Value : na, color=_SuperTrend2_Color, linewidth=1, style = plot.style_linebr, title="🌊 TimeFrame #2 🌊 Long SuperTrend", join = true)
ST2_Short = plot(SuperTrend2_Enabled and SuperTrend2_Direction < 0 ? SuperTrend2_Value : na, color=_SuperTrend2_Color, linewidth=1, style = plot.style_linebr, title="🌊 TimeFrame #2 🌊 Short SuperTrend", join = true)
fill(ST2_Long, bodyMiddle, color = color.new(_SuperTrend2_Color, 90),fillgaps = false, display = fill_SuperTrends ? display.all : display.none)
fill(ST2_Short, bodyMiddle, color = color.new(_SuperTrend2_Color, 90),fillgaps = false, display = fill_SuperTrends ? display.all : display.none)



SuperTrend3_Enabled = input.bool(true, "✅ Enable", group="🌊 TimeFrame #3 🌊")
SuperTrend3_Timeframe = input.timeframe("1D", "  🥽 Timeframe", group="🌊 TimeFrame #3 🌊")
SuperTrend3_Period = input.int(50, "  🔎 Period", group="🌊 TimeFrame #3 🌊")
SuperTrend3_Factor = input.float(3.0, "  ⚙️ Factor", group="🌊 TimeFrame #3 🌊")
SuperTrend3_BullishColor = input.color(color.rgb(54, 211, 58), "    🖌️ Bullish Color", group="🌊 TimeFrame #3 🌊", inline="Colors")
SuperTrend3_BearishColor = input.color(color.rgb(211, 61, 61), "    🖌️ Bearish Color", group="🌊 TimeFrame #3 🌊", inline="Colors")
SuperTrend3_LabelEnabled = input.bool(true, "✅ Enable Label", group="🌊 TimeFrame #3 🌊")
SuperTrend3_LabelSize = input.string("Normal", "  📐 Size", options=["Auto", "Tiny", "Small", "Normal", "Large", "Huge"], group="🌊 TimeFrame #3 🌊")
SuperTrend3_LabelOffsetInBars = input.int(35, "  📏 Label Offset (in Bars)", group="🌊 TimeFrame #3 🌊")
SuperTrend3_ShowLabelLine = input.bool(true, "✅ Show Label Line", group="🌊 TimeFrame #3 🌊")

SuperTrend3_Hidden = hideLowerTimeframes and (timeframe.in_seconds() > timeframe.in_seconds(SuperTrend3_Timeframe))
_SuperTrend3_BearishColor = enableColorTheme ? bearishColor : SuperTrend3_BearishColor
_SuperTrend3_BullishColor = enableColorTheme ? bullishColor : SuperTrend3_BullishColor
[_SuperTrend3_Value, _SuperTrend3_Direction] =  request.security(syminfo.ticker, SuperTrend3_Timeframe, ta.supertrend(SuperTrend3_Factor, SuperTrend3_Period), barmerge.gaps_off, barmerge.lookahead_off)
SuperTrend3_Value = SuperTrend3_Enabled and not SuperTrend3_Hidden ? _SuperTrend3_Value : na
SuperTrend3_Direction = SuperTrend3_Enabled and not SuperTrend3_Hidden ? _SuperTrend3_Direction : na
SuperTrend3_Color = SuperTrend3_Direction > 0 ? _SuperTrend3_BullishColor : _SuperTrend3_BearishColor
_SuperTrend3_Color = SuperTrend3_Color
ST3_Long = plot(SuperTrend3_Enabled and SuperTrend3_Direction > 0 ? SuperTrend3_Value : na, color=_SuperTrend3_Color, linewidth=1, style = plot.style_linebr, title="🌊 TimeFrame #3 🌊 Long SuperTrend", join = true)
ST3_Short = plot(SuperTrend3_Enabled and SuperTrend3_Direction < 0 ? SuperTrend3_Value : na, color=_SuperTrend3_Color, linewidth=1, style = plot.style_linebr, title="🌊 TimeFrame #3 🌊 Short SuperTrend", join = true)
fill(ST3_Long, bodyMiddle, color = color.new(_SuperTrend3_Color, 90), fillgaps = false, display = fill_SuperTrends ? display.all : display.none)
fill(ST3_Short, bodyMiddle, color = color.new(_SuperTrend3_Color, 90), fillgaps = false, display = fill_SuperTrends ? display.all : display.none)

// Labels
var SuperTrend1_Label = label(na)
var SuperTrend1_Label_Line = line(na)

var SuperTrend2_Label = label(na)
var SuperTrend2_Label_Line = line(na)

var SuperTrend3_Label = label(na)
var SuperTrend3_Label_Line = line(na)

if (barstate.islast)
    if (SuperTrend1_LabelEnabled and SuperTrend1_Enabled)
        if (not na(SuperTrend1_Label))
            label.delete(SuperTrend1_Label)
            line.delete(SuperTrend1_Label_Line)
        if (SuperTrend1_ShowLabelLine)
            SuperTrend1_Label_Line := line.new(bar_index, SuperTrend1_Value, bar_index + SuperTrend1_LabelOffsetInBars, SuperTrend1_Value,
              xloc=xloc.bar_index, extend=extend.none, color=_SuperTrend1_Color, width=1, style=line.style_dashed)
        SuperTrend1_Label := label.new(bar_index + SuperTrend1_LabelOffsetInBars, SuperTrend1_Value, color=color.new(color.rgb(0,0,0),100), style=label.style_label_left, text="〽️ " + tfString(SuperTrend1_Timeframe) + " " + str.tostring(SuperTrend1_Period) + "/" + str.tostring(SuperTrend1_Factor) + " SuperTrend ➜ " + str.tostring(math.round_to_mintick(SuperTrend1_Value)), 
          textcolor=_SuperTrend1_Color, size=getSize(SuperTrend1_LabelSize))

    if (SuperTrend2_LabelEnabled and SuperTrend2_Enabled)
        if (not na(SuperTrend2_Label))
            label.delete(SuperTrend2_Label)
            line.delete(SuperTrend2_Label_Line)
        if (SuperTrend2_ShowLabelLine)
            SuperTrend2_Label_Line := line.new(bar_index, SuperTrend2_Value, bar_index + SuperTrend2_LabelOffsetInBars, SuperTrend2_Value,
              xloc=xloc.bar_index, extend=extend.none, color=_SuperTrend2_Color, width=1, style=line.style_dashed)
        SuperTrend2_Label := label.new(bar_index + SuperTrend2_LabelOffsetInBars, SuperTrend2_Value, color=color.new(color.rgb(0,0,0),100), style=label.style_label_left, text="〽️ " + tfString(SuperTrend2_Timeframe) + " " + str.tostring(SuperTrend2_Period) + "/" + str.tostring(SuperTrend2_Factor) + " SuperTrend ➜ " + str.tostring(math.round_to_mintick(SuperTrend2_Value)), 
          textcolor=_SuperTrend2_Color, size=getSize(SuperTrend2_LabelSize))
    
    if (SuperTrend3_LabelEnabled and SuperTrend3_Enabled)
        if (not na(SuperTrend3_Label))
            label.delete(SuperTrend3_Label)
            line.delete(SuperTrend3_Label_Line)
        if (SuperTrend3_ShowLabelLine)
            SuperTrend3_Label_Line := line.new(bar_index, SuperTrend3_Value, bar_index + SuperTrend3_LabelOffsetInBars, SuperTrend3_Value,
              xloc=xloc.bar_index, extend=extend.none, color=_SuperTrend3_Color, width=1, style=line.style_dashed)
        SuperTrend3_Label := label.new(bar_index + SuperTrend3_LabelOffsetInBars, SuperTrend3_Value, color=color.new(color.rgb(0,0,0),100), style=label.style_label_left, text="〽️ " + tfString(SuperTrend3_Timeframe) + " " + str.tostring(SuperTrend3_Period) + "/" + str.tostring(SuperTrend3_Factor) + " SuperTrend ➜ " + str.tostring(math.round_to_mintick(SuperTrend3_Value)), 
          textcolor=_SuperTrend3_Color, size=getSize(SuperTrend3_LabelSize))

