//@version=5
library("ttbcolors", overlay = true)

export colorUp() =>
    color.new(color.rgb(20, 225, 255), 0)

export colorDown() =>
    color.new(color.rgb(191, 54, 255), 0)

export colorUplight() =>
    color.new(#74ecff, 0)

export colorDownlight() =>
    color.new(#e4acfe, 0)

export colorNeutral() =>
    color.new(color.rgb(255, 209, 184), 0)

export colorUpPlus() =>
    color.new(color.rgb(76, 161, 255), 0)

export colorDownPlus() =>
    color.new(color.rgb(220, 56, 250), 0)

export colorUptrans() =>
    color.new(color.rgb(20, 225, 255), 85)

export colorDowntrans() =>
    color.new(color.rgb(191, 54, 255), 85)

export colorNeutraltrans() =>
    color.new(color.rgb(255, 209, 184), 85)

export colorUpPlustrans() =>
    color.new(color.rgb(76, 161, 255), 85)

export colorDownPlustrans() =>
    color.new(color.rgb(220, 56, 250), 85)

export colorBlackish() =>
    color.new(color.rgb(220, 56, 250), 0)